name: pipeline_ETL_ANTAQ

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  testar-hmg:
    runs-on: ubuntu-latest
    environment:
      name: homologacao
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: ./
        with:
          dag_file: dags/Resposta_4.py
          docker_file: docker-compose.yaml
          dag_path: dags/
          plugin_path: plugins/
  empacotar-hmg:
    runs-on: ubuntu-latest
    environment: 
      name: homologacao
    needs: testar-hmg
    steps:
      - name: Empacotando
        run: echo empacotado

  distribuir-hmg:
    runs-on: ubuntu-latest
    environment:
      name: homologacao
    needs: empacotar-hmg
    steps:
      - name: Distribuir
        run: echo distribuindo...

  testar-prod:
    runs-on: ubuntu-latest
    environment:
      name: producao
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Validate DAGs'
        uses: ./
        with:
          dag_file: dags/Resposta_4.py
          docker_file: docker-compose.yaml
          dag_path: dags/
          plugin_path: plugins/

  empacotar-prod:
    runs-on: ubuntu-latest
    environment:
      name: producao
    needs: testar-prod
    steps:
      - name: Empacotando
        run: echo empacotado
  distribuir-prod:
    runs-on: ubuntu-latest
    environment:
      name: producao
    needs: empacotar-prod
    steps:
      - name: Distribuir
        run: echo distribuindo
